### Welcome to first hands-On on CNN.   
In this hands-on you will be implementing padding, convolution and pooling operation using numpy.
- Follow the comments provided for each cell to code accordingly.
- To run the code in the cell press **shift+enter**. Make sure you do this for each cell

- Run the bellow cell to import necessary packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

- Read the image file '**home.png**'(in current directory) using **mpimg.imread("file_path")** function provided by matplotlib.image module. This function reads the image and returns the pixel intensities in numpy format. Assign this result to variable **img**.
- The dimension of **img** will now be $n_H$ x $n_w$ x $n_c$
- reshape **img** to dimension $m$ x $n_H$ x $n_w$ x $n_c$ and assign it to variable **data**. The dimension **m** will be **one** since we are dealing with one image data. (use numpy's reshape())

Expected output:   
**class 'numpy.ndarray'**  
**Image dimension  (252, 362, 3)**  
**input data dimension  (1, 252, 362, 3)**     

In [5]:
###Start code here
img = 
data = 
###End code

print(type(img))
print("Image dimension ",img.shape)
print("Input data dimension ", data.shape)

<class 'numpy.ndarray'>
Image dimension  (252, 362, 3)


- Run the below cell to view the image from the data

In [ ]:
plt.imshow(data[0,:,:,:])
plt.grid(False)
plt.axis("off")

### zero padding
- Define method named zero_pad that performs specified number of zero padding on the input data.  
parameters: 
            data: the data on which padding is performed    
            pad:  the amount of padding around the data    
returns: 
            data_padded: the nd-array after padding  

In [ ]:
def zero_pad(data, pad):
    ###Start code here
    data_padded = 
    return data_padded
    ###End code

- Run the below cell to add zero zero padding using the method define above.   
Expected output:
             [[0. 0. 0. 0.]
             [0. 0. 0. 0.]
             [0. 0. 1. 1.]
             [0. 0. 1. 1.]]

In [ ]:
print("dimension before padding: ", data.shape)
img_pad = zero_pad(data, 10)
print("dimension after padding: ", img_pad.shape)
print(img_pad[0,8:12,8:12,1])
plt.imshow(img_pad[0,:,:,:], cmap = "gray")
plt.grid(False)

output1 = np.mean(img_pad)

### Convolution single step  
Define the function named conv_single_step() to convolve a slice of input data using the specified filter  
parameter:  
         - data_slice: the receptive field over which convolution is performed  
         - W: the filter used for convolution  
         - b: the bias term  
returns:
         - Z: convolved output over the receptive field

In [ ]:
def conv_single_step(data_slice, W, b):
    ###Start code
    conv = 
    Z = 
    ###End code
    return Z

### Strided Convolution
Define method conv_forward to perform strided convolution on the input data.  
use conv_single_step() to perform the convolution at each stride.  
Parameters:  
        - data: input data on which convolution is performed  
        - W: the filter used for convolution operation  
        - b: the bias term  
        - hparams: dictionary defined by {"stride": s, "pad": p}  
returns:  
       - Z: the convolved output  

refer the code snippet provided in the course.  

In [ ]:
def conv_forward(data, W, b, hparams):
    ###Start code here
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    ###End code
    return Z ##(convolved output)

- The below cell defines the test data for input as well as filter.  
- Run the cell to perfom the convolution operation using the method defined above.   
**Expected output: 0.145**
               

In [ ]:
np.random.seed(1)
input_ = np.random.randn(10, 4, 4, 3)
W = np.random.randn(2, 2, 3, 8)
b = np.random.randn(1, 1, 1, 8)
hparameters = {"pad" : 1,
               "stride": 1}

output_ = conv_forward(input_, W, b, hparameters)
print(np.mean(output_))

- Run the below cell to define edge_detect filter, the filter values for edge detection has been define for you

In [ ]:
edge_detect = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]]).reshape((3,3,1,1))

- Define a dictionary hparams with stride = 1 and pad = 0
- initialize bias parameter b to zero of dimension (1,1,1,1) hint: use np.zeros()
- Perform strided convolution using the method conv_forward() you defined previously.
  - pass edge_detect filter, bais b and hparams as parameters to perform convolution on the data variable defined previously.
  - assign the result to variable Z

In [ ]:
###Start code
hparams = 
b = 
Z = 


plt.clf()
plt.imshow(Z[0,:,:,0], cmap='gray',vmin=0, vmax=1)
plt.grid(False)
print("dimension of image before convolution: ", data.shape)
print("dimension of image after convolution: ", Z.shape)

output2 = np.mean(Z[0,100:200,200:300,0])


##below are the filters for vetical as well as horizontal edge detection, try these filters once you have completed this handson.
##vertical_filter = np.array([[-1,2,-1],[-1,2,-1],[-1,2,-1]]).reshape(3,3,1,1)
##horizontal_filter = np.array([[-1,-1,-1],[2,2,2],[-1,-1,-1]]).reshape((3,3,1,1))

### Max pooling
Define method max_pool to perform max pooling on the input data.  
Parameters:  
        - data: input data on which convolution is performed  
        - hparams: dictionary defined by {"f": f, "stride": s} , f is the filter size and s              the number of strides
returns:  
       - output: output after pooling 

refer the code snippet provided in the course.  

In [ ]:
def max_pool(input, hparam):
    ###start code
    
    
    
    
    
    
    
    
    
    
    
    ###End code
    return output

- Run the below cell to test the method you define above.  
Expected output: **1.075**

In [ ]:
pool_params = {"stride" : 2, "f" : 2}
output_ = max_pool(input_, pool_params)
print(np.mean(output_))

- Define pooling parameters "stride" and filter size "f" as a dictionary named **hparams** with stride = 1 and f = 2
- call the method max_pool with parameters Z (the convolved output) and hparams 

In [ ]:
###start code
hparams = 
Z_pool = 
###End code

print("dimension before pooling :", Z.shape)
print("dimension after pooling :", Z_pool.shape)

plt.imshow(Z_pool[0,:,:,0], cmap = "gray")

with open("output.txt", "w+") as file:
    file.write("output1 = %f" %output1)
    file.write("\noutput2 = %f" %output2)